{
  lib,
  mapContainerRuntimeArtifactContext,
  mapContainerRuntimeArtifactTree,
}:
{
  normalizedModel,
  enterpriseName,
  siteName,
  hostName,
  containerName,
  runtimeTargetName,
  runtimeTarget,
}:
let
  artifactContext = mapContainerRuntimeArtifactContext {
    inherit
      enterpriseName
      siteName
      hostName
      containerName
      runtimeTargetName
      runtimeTarget
      ;
  };
in
mapContainerRuntimeArtifactTree {
  inherit
    normalizedModel
    artifactContext
    ;
}
